export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
export const SIGN_UP_BEGIN = "SIGN_UP_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const MAKE_PAYMENT_BEGIN = "MAKE_PAYMENT_BEGIN";
export const MAKE_PAYMENT_FAILURE = "MAKE_PAYMENT_FAILURE";
export const MAKE_PAYMENT_SUCCESS = "MAKE_PAYMENT_SUCCESS";
export const GET_ALL_SPECIALISTS_SUCCESS = "GET_ALL_SPECIALIST_SUCCESS";
export const GET_ALL_SERVICES_SUCCESS = "GET_ALL_SERVICES_SUCCESS";
export const GET_ALL_SPECIALISTS_FAILURE = "GET_ALL_SPECIALIST_FAILURE";
export const GET_ALL_SERVICES_FAILURE = "GET_ALL_SERVICES_FAILURE";
export const GET_ALL_SPECIALISTS_BEGIN = "GET_ALL_SPECIALIST_BEGIN";
export const GET_ALL_SERVICES_BEGIN = "GET_ALL_SERVICES_BEGIN";
export const CREATE_BOOKING_BEGIN = "CREATE_BOOKING_BEGIN";
export const CREATE_BOOKING_FAILURE = "CREATE_BOOKING_FAILURE";
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const SELECTED_DAY_SUCCESS = "SELECTED_DAY_SUCCESS";
export const SELECTED_SLOT_SUCCESS = "SELECTED_SLOT_SUCCESS";
export const SET_SELECTED_SPECIALIST_SUCCESS =
  "SET_SELECTED_SPECIALIST_SUCCESS";
export const CREATE_APPOINTMENT_BEGIN = "CREATE_APPOINTMENT_BEGIN";
export const CREATE_APPOINTMENT_FAILURE = "CREATE_APPOINTMENT_FAILURE";
export const CREATE_APPOINTMENT_SUCCESS = "CREATE_APPOINTMENT_SUCCESS";
export const SET_CATEGORY_SUCCESS = "SET_CATEGORY_SUCCESS";
export const SET_SELECTED_CARD = "SET_SELECTED_CARD";
export const SET_APTMNT_BTN = "SET_APTMNT_BTN";

const types = {
  SIGN_UP_BEGIN,
  SIGN_UP_SUCCESS,
  SIGN_UP_FAILURE,
  LOGIN_BEGIN,
  LOGIN_FAILURE,
  LOGIN_SUCCESS,
  GET_ALL_SPECIALISTS_BEGIN,
  GET_ALL_SPECIALISTS_FAILURE,
  GET_ALL_SPECIALISTS_SUCCESS,
  MAKE_PAYMENT_BEGIN,
  MAKE_PAYMENT_FAILURE,
  MAKE_PAYMENT_SUCCESS,
  GET_ALL_SERVICES_BEGIN,
  GET_ALL_SERVICES_SUCCESS,
  GET_ALL_SERVICES_FAILURE,
  CREATE_BOOKING_BEGIN,
  CREATE_BOOKING_FAILURE,
  CREATE_BOOKING_SUCCESS,
  CREATE_APPOINTMENT_BEGIN,
  CREATE_APPOINTMENT_FAILURE,
  CREATE_APPOINTMENT_SUCCESS,
  SELECTED_DAY_SUCCESS,
  SET_SELECTED_SPECIALIST_SUCCESS,
  SELECTED_SLOT_SUCCESS,
  SET_CATEGORY_SUCCESS,
  SET_SELECTED_CARD,
  SET_APTMNT_BTN,
};

export default types;
